version: '3.4'
services:
    tokengenerator_docker:
        image: node:alpine
        container_name: SYS-TokenGenerator
        command: /bin/sh -c "cd /srv/app && npm install && node index.js"
        ports:
            - 3001:3001
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
